[versions]
gradle = "8.13.0"
google-services = "4.4.4"
androidx-activity-compose = "1.11.0"
coroutines = "1.10.2"
ktor = "3.3.1"
kotlin = "2.2.20"
material = "1.13.0"
koin = "4.1.1"
room = "2.8.3"
sqlite = "2.6.1"
ksp = "2.2.20-2.0.4"
firebase= "34.4.0"
firebase-kotlin = "1.13.0"
firebase-auth-android = "24.0.1"
firebase-common-android = "22.0.1"
firebase-firestore-android = "26.0.2"
firebase-functions-android = "22.0.1"
firebase-storage-android = "22.0.1"
firebase-analytics-android = "22.5.0"
libphonenumber = "9.0.17"
kotlinDateTime = "0.7.1"
compose-multiplatform = "1.9.1"
spotless = "6.25.0"
kotlinx-serialization = "1.7.3"
androidxTestCore = "1.5.0"
androidxTestExtJunit = "1.1.5"
robolectric = "4.12.2"
composeUi = "1.9.3"

# @keep
minSdk = "24"
# @keep
targetSdk = "36"
# @keep
compileSdk = "36"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUi" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUi" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
google-android-material = { module = "com.google.android.material:material", version.ref = "material" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDateTime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth-android" }
firebase-common = { module = "com.google.firebase:firebase-common", version.ref = "firebase-common-android" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebase-firestore-android" }
firebase-functions = { module = "com.google.firebase:firebase-functions", version.ref = "firebase-functions-android" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebase-storage-android" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase-analytics-android" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-common-kt = { module = "dev.gitlive:firebase-common", version.ref = "firebase-kotlin" }
firebase-app-kt = { module = "dev.gitlive:firebase-app", version.ref = "firebase-kotlin" }
firebase-auth-kt = { module = "dev.gitlive:firebase-auth", version.ref = "firebase-kotlin" }
firebase-firestore-kt = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase-kotlin" }
firebase-functions-kt = { module = "dev.gitlive:firebase-functions", version.ref = "firebase-kotlin" }
firebase-storage-kt = { module = "dev.gitlive:firebase-storage", version.ref = "firebase-kotlin" }
firebase-storage-android = { module = "com.google.firebase:firebase-storage-ktx", version = "21.0.1" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
